---
title: "R Data Visualisation Library"
subtitle: "A NHSE Regional Collaboration"
date:  "16/05/2024"
published-title: "Last updated"
author: "A collaboration proof of concept between East of England Intelligence & Insight and North East & Yorkshire Analytics Team"
date-format: "D MMMM YYYY"
format:
  html:
    grid:
      sidebar-width: 300px
      body-width: 1100px
      margin-width: 100px
      gutter-width: 1.5rem
  # Table of Contents options
    toc: true
    toc-depth: 4
    toc-location: left
    toc-title: Contents
    number-sections: false
    number-depth: 3
  # Render options
    theme: cosmo
    css: EoE_report_theme.css
    anchor-sections: false
    html-math-method: katex
  # Code options
    code-tools:
      source: false
      toggle: false
      caption: none
    embed-resources: true
    standalone: true
    link-external-icon: true
    link-external-newwindow: true
    # Reference options
    citations-hover: true
    footnotes-hover: true
    # Callout options
    callout-appearance: simple
    callout-collapse: true
    # Caption options
    cap-location: bottom
    # Title options
    title-block-banner: '#005EB8'
    backgroundcolor: '#f0f4f5'
   # backgroundcolor: white
    # Set font
    mainfont: 'Open Sans'
execute:
  echo: false
crossref:
  fig-title: '**Figure**'
  fig-labels: arabic
filters:
  - quarto_callouts.lua
---

# Overview

This library provides example visualisations to browse with associated R code & example datasets (sourced from published data using different NHS geographies).

# Review Management

| Latest Review Date | Comment               |
|--------------------|-----------------------|
| 16/05/2024         | Creation of document. |

# Useful Links

The R Graph Library ([r-graph-gallery.com/](https://r-graph-gallery.com/)) Github: https://github.com/holtzy/R-graph-gallery

Consolidated Data sets for UDAL, NCDR and SIP (<https://future.nhs.uk/NCDR/view?objectId=54791205#54791205>)

# Distribution

## Violin

{Insert example image here}

::: {.callout-note collapse="true"}
## **Example Dataset**

The dataset that has been used in the R code is located here: {Insert link}
:::

::: {.callout-note collapse="true"}
## **R Code**

The R code that has been used to create this visualisation is located here: {Insert link}
:::

::: panel-tabset
## Histogram

{Insert example image here}

::: {.callout-note collapse="true"}
## **Example Dataset**

The dataset that has been used in the R code is located here: {Insert link}
:::

::: {.callout-note collapse="true"}
## **R Code**

The R code that has been used to create this visualisation is located here: {Insert link}
:::

:::

# Metadata

> Title: East of England Data Documentation\
> General Contact: [**East of England Intelligence and Insight Team**](#0)\
> Technical Contact: [**ruby.nicholls\@nhs.net**](ruby.nicholls@nhs.net)\
> Version DRAFT 1.0\
> Latest Development: 27/02/2024
